"""
HiResCAM — High-Resolution Class Activation Mapping.

Unlike Grad-CAM (which averages gradients spatially, then multiplies with
activations), HiResCAM element-wise multiplies gradients *with* activations
before spatial reduction.  This yields sharper, more pixel-accurate heatmaps
that are provably faithful to the model's decision for a single convolutional
layer (Draelos & Carin, ICCV 2021).

Also provides:
    - quantitative localization scoring (IoU, Dice, Pointing-Game)
      against the lesion masks generated by Module 2 (structures.py)
    - DualCAM: runs Grad-CAM + HiResCAM together, returns both overlays
      and a comparison analysis for the takeaway report.
"""

from __future__ import annotations

import cv2
import numpy as np
import torch
import torch.nn.functional as F

from engine.pipeline.grading import DRGradingModel


# ---------------------------------------------------------------------------
# HiResCAM
# ---------------------------------------------------------------------------

class HiResCAM:
    """HiResCAM on the last EfficientNet feature block.

    Key difference from Grad-CAM
    ----------------------------
    Grad-CAM:   weights = GAP(grads)  →  cam = ReLU( Σ_c weights_c · A_c )
    HiResCAM:   cam = ReLU( Σ_c (grad_c ⊙ A_c) )   (element-wise first)

    The element-wise product preserves spatial structure that GAP destroys,
    producing higher-resolution saliency maps.
    """

    def __init__(self, model: DRGradingModel, target_layer_index: int = -1):
        self.model = model
        self.activations: torch.Tensor | None = None
        self.gradients: torch.Tensor | None = None

        layer = model.features[target_layer_index]
        layer.register_forward_hook(self._fwd_hook)
        layer.register_full_backward_hook(self._bwd_hook)

    # -- hooks ---------------------------------------------------------------
    def _fwd_hook(self, _m, _i, output):
        self.activations = output.detach()

    def _bwd_hook(self, _m, _gi, grad_output):
        self.gradients = grad_output[0].detach()

    # -- compute -------------------------------------------------------------
    def compute(
        self,
        x: torch.Tensor,
        lesion_feats: torch.Tensor | None,
        head: str = "referable",
    ) -> np.ndarray:
        """Return a [0, 1] saliency map resized to the input spatial dims."""
        self.model.eval()
        x = x.clone().requires_grad_(True)
        ord_logits, ref_logits = self.model(x, lesion_feats)

        score = ref_logits.sum() if head == "referable" else ord_logits.sum()
        self.model.zero_grad(set_to_none=True)
        score.backward()

        # ── HiResCAM core: element-wise product instead of GAP weighting ──
        # activations shape: (B, C, H, W)
        # gradients   shape: (B, C, H, W)
        elementwise = self.gradients * self.activations        # (B, C, H, W)
        cam = F.relu(elementwise.sum(dim=1)).squeeze(0)        # (H, W)

        cam = cam - cam.min()
        cam = cam / (cam.max() + 1e-9)
        cam = cam.cpu().numpy()

        return cv2.resize(
            cam, (x.shape[3], x.shape[2]), interpolation=cv2.INTER_LINEAR
        )


# ---------------------------------------------------------------------------
# Localization scoring — quantitative explainability metrics
# ---------------------------------------------------------------------------

def compute_localization_score(
    cam: np.ndarray,
    lesion_masks: dict[str, np.ndarray],
    threshold: float = 0.4,
) -> dict:
    """Compute IoU, Dice and Pointing-Game metrics between a CAM and lesion masks.

    Parameters
    ----------
    cam : (H, W) float32 in [0, 1]
    lesion_masks : {"microaneurysms": ..., "hemorrhages": ..., "exudates": ...}
        Binary uint8 masks from Module 2 (structures.py).
    threshold : float
        Binarisation threshold for the CAM.

    Returns
    -------
    dict with per-lesion and aggregate metrics.
    """
    cam_binary = (cam >= threshold).astype(np.uint8)
    results: dict = {}
    all_iou, all_dice, all_pg = [], [], []

    for name, mask in lesion_masks.items():
        if mask is None or mask.max() == 0:
            continue

        # Resize mask to match CAM resolution if needed
        if mask.shape[:2] != cam.shape[:2]:
            mask = cv2.resize(
                mask, (cam.shape[1], cam.shape[0]),
                interpolation=cv2.INTER_NEAREST,
            )

        mask_bin = (mask > 0).astype(np.uint8)

        # IoU
        intersection = int((cam_binary & mask_bin).sum())
        union = int((cam_binary | mask_bin).sum())
        iou = intersection / max(union, 1)

        # Dice (F1)
        dice = (2 * intersection) / max(int(cam_binary.sum()) + int(mask_bin.sum()), 1)

        # Pointing Game: does the CAM peak land inside any lesion pixel?
        peak_y, peak_x = np.unravel_index(np.argmax(cam), cam.shape)
        pointing_hit = bool(mask_bin[peak_y, peak_x] > 0)

        results[name] = {
            "iou": round(float(iou), 4),
            "dice": round(float(dice), 4),
            "pointing_game": pointing_hit,
            "cam_coverage": round(float(intersection / max(int(mask_bin.sum()), 1)), 4),
        }
        all_iou.append(iou)
        all_dice.append(dice)
        all_pg.append(1.0 if pointing_hit else 0.0)

    # Aggregate (macro average over lesion types that exist)
    if all_iou:
        results["aggregate"] = {
            "mean_iou": round(float(np.mean(all_iou)), 4),
            "mean_dice": round(float(np.mean(all_dice)), 4),
            "pointing_game_accuracy": round(float(np.mean(all_pg)), 4),
        }
    else:
        results["aggregate"] = {
            "mean_iou": 0.0,
            "mean_dice": 0.0,
            "pointing_game_accuracy": 0.0,
            "_note": "No lesion masks with positive pixels available for scoring.",
        }

    return results


# ---------------------------------------------------------------------------
# DualCAM — run both Grad-CAM and HiResCAM, return comparative analysis
# ---------------------------------------------------------------------------

class DualCAM:
    """Convenience wrapper: runs both Grad-CAM and HiResCAM in a single call."""

    def __init__(self, model: DRGradingModel, target_layer_index: int = -1):
        # We need *separate* hook registrations, so we instantiate both
        # on separate copies of the layer reference.  Because hooks are
        # additive, a single forward-backward pass records for both.
        from engine.pipeline.explain import GradCAM

        self.gradcam = GradCAM(model, target_layer_index)
        self.hirescam = HiResCAM(model, target_layer_index)

    def compute(
        self,
        x: torch.Tensor,
        lesion_feats: torch.Tensor | None,
        head: str = "referable",
    ) -> dict:
        """Return both CAMs and their per-lesion localization comparison."""
        cam_grad = self.gradcam.compute(x.clone(), lesion_feats, head)
        cam_hires = self.hirescam.compute(x.clone(), lesion_feats, head)
        return {
            "gradcam": cam_grad,
            "hirescam": cam_hires,
        }

    def compute_with_scores(
        self,
        x: torch.Tensor,
        lesion_feats: torch.Tensor | None,
        lesion_masks: dict[str, np.ndarray],
        head: str = "referable",
        threshold: float = 0.4,
    ) -> dict:
        """Compute both CAMs plus localization metrics for each."""
        cams = self.compute(x, lesion_feats, head)
        cams["gradcam_scores"] = compute_localization_score(
            cams["gradcam"], lesion_masks, threshold
        )
        cams["hirescam_scores"] = compute_localization_score(
            cams["hirescam"], lesion_masks, threshold
        )
        return cams


def make_hirescam_overlay(
    img_bgr: np.ndarray, cam: np.ndarray, alpha: float = 0.45
) -> np.ndarray:
    """Apply a JET-coloured HiResCAM overlay onto the original image."""
    heat = cv2.applyColorMap((cam * 255).astype(np.uint8), cv2.COLORMAP_JET)
    if img_bgr.shape[:2] != heat.shape[:2]:
        heat = cv2.resize(heat, (img_bgr.shape[1], img_bgr.shape[0]))
    return cv2.addWeighted(img_bgr, 1 - alpha, heat, alpha, 0)
