"""
MedGemma Vision-Language Multimodal Diagnostic Report Generator (Tier 2).

Sends the retinal fundus image, HiResCAM saliency map, and Tier 1 structured
features (ordinal grade, lesion counts, vessel geometry, localization scores)
to MedGemma's multimodal API for a grounded clinical explanation.

Falls back gracefully to Tier 1 offline template report if:
- OFFLINE_MODE is True
- Network is unreachable or timed out
- No API keys are available or rate limits exceeded
"""

from __future__ import annotations

import base64
import json
import logging
import re
import time
from pathlib import Path
from typing import Any

import cv2
import numpy as np
import requests

from config import (
    get_next_gemma_key,
    GEMMA_MODEL_NAME,
    MEDGEMMA_MODEL_NAME,
    OFFLINE_MODE,
    TIER2_TIMEOUT,
    DR_STAGES,
)
from engine.pipeline.offline_report import generate_offline_report

log = logging.getLogger("MedGemmaTier2")

GEMMA_API_URL = "https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent"

MEDGEMMA_SYSTEM_PROMPT = """You are DrishtiAI's MedGemma Clinical Decision Support System — an advanced medical vision-language model evaluating Diabetic Retinopathy (DR) screening cases for rural healthcare centers.

You are provided with:
1. High-resolution retinal fundus photograph.
2. High-Resolution Class Activation Map (HiResCAM / Grad-CAM) highlighting areas that drove the AI's diagnostic prediction.
3. Structured quantitative findings from the Tier 1 edge pipeline (stage prediction, calibrated probabilities, lesion counts, vessel metrics, and localization scores).

YOUR RESPONSIBILITIES:
1. VISUAL VERIFICATION: Examine the retinal photograph and verify whether the AI's grade is supported by visible pathological features (microaneurysms, hemorrhages, hard/soft exudates, venous beading, IRMA, neovascularization).
2. HEATMAP CORRELATION: Correlate the activation regions in the heatmap with actual retinal anatomy and lesions. Confirm if the model is attending to true pathological hallmarks or imaging artifacts.
3. CLINICAL NARRATIVE: Provide clear, empathetic, and evidence-grounded clinical commentary explaining the rationale in plain language suitable for rural healthcare workers and patients.
4. ACTIONABLE GUIDANCE: Detail explicit follow-up urgency, referral timelines, and lifestyle/glycemic guidance based on ETDRS and International Clinical Diabetic Retinopathy (ICDR) standards.

SAFETY AND ETHICAL CONSTRAINTS:
- NEVER state definitively "you have" or "you are diagnosed with". Always use "the screening indicates" or "clinical findings are consistent with".
- Always include an appropriate clinical disclaimer.
- Output MUST be strictly valid JSON matching the exact schema specified below. No preamble, no markdown formatting outside JSON.

OUTPUT JSON SCHEMA:
{
  "current_diagnosis": {
    "stage": <int 0-4>,
    "stage_name": "<string>",
    "confidence": "<string like 94.2%>",
    "plain_language": "<2-3 sentence patient-friendly summary>",
    "clinical_rationale": "<detailed clinical explanation referencing visible lesions>"
  },
  "visual_verification": {
    "agreement_with_ai": "<STRONG_AGREEMENT | MODERATE_AGREEMENT | DISCREPANCY_SUSPECTED>",
    "pathology_observed": ["<finding 1>", "<finding 2>", "..."],
    "heatmap_faithfulness": "<Assessment of whether heatmap accurately localizes true lesions>"
  },
  "visual_findings": {
    "heatmap_summary": "<What the saliency map highlights and its anatomical location>",
    "vessel_analysis": "<Evaluation of vascular caliber, branching, tortuosity, or neovascularization>"
  },
  "risk_prediction": {
    "6_month": {
      "progression_risk_percent": "<range like 12-18%>",
      "scenario_if_untreated": "<1-2 sentences>",
      "scenario_if_managed": "<1-2 sentences>"
    },
    "12_month": {
      "progression_risk_percent": "<range like 20-30%>",
      "scenario_if_untreated": "<1-2 sentences>",
      "scenario_if_managed": "<1-2 sentences>"
    }
  },
  "action_plan": [
    "<action 1>",
    "<action 2>",
    "<action 3>",
    "<action 4>",
    "<action 5>"
  ],
  "urgency": "<ROUTINE | SOON | URGENT | EMERGENCY>",
  "recommended_follow_up": "<Specific timeframe e.g. 'Referral to ophthalmology clinic within 3-4 weeks'>",
  "diet_recommendations": [
    "<diet item 1>",
    "<diet item 2>",
    "<diet item 3>"
  ],
  "disclaimer": "This is an AI-assisted screening assessment generated by the DrishtiAI Two-Tiered diagnostic system. It does NOT replace a comprehensive dilated eye examination by a certified ophthalmologist or retina specialist."
}
"""


def encode_image_to_base64(image: str | Path | np.ndarray) -> str:
    """Encode an image path or numpy BGR array to a base64 string."""
    if isinstance(image, (str, Path)):
        img_path = Path(image)
        if not img_path.exists():
            raise FileNotFoundError(f"Image not found at {img_path}")
        with open(img_path, "rb") as f:
            return base64.b64encode(f.read()).decode("utf-8")
    elif isinstance(image, np.ndarray):
        # Encode numpy array as JPEG
        success, buffer = cv2.imencode(".jpg", image, [cv2.IMWRITE_JPEG_QUALITY, 90])
        if not success:
            raise ValueError("Failed to encode numpy image array to JPEG")
        return base64.b64encode(buffer).decode("utf-8")
    else:
        raise TypeError(f"Unsupported image type: {type(image)}")


def _build_user_prompt(
    detection_result: dict,
    structures: dict | None,
    localization_metrics: dict | None,
    patient_info: dict | None,
) -> str:
    """Assemble the structured prompt combining all Tier 1 findings."""
    stage = detection_result.get("stage", 0)
    stage_name = detection_result.get("stage_name", DR_STAGES.get(stage, {}).get("name", "Unknown"))
    conf = detection_result.get("confidence", "N/A")
    probs = detection_result.get("all_probabilities", detection_result.get("probs", {}))

    prompt_lines = [
        "TIER 1 EDGE ANALYSIS RESULTS:",
        f"- Predicted Grade: Stage {stage} ({stage_name})",
        f"- Estimated Confidence: {conf}%",
        f"- Class Probability Distribution: {json.dumps(probs)}",
    ]

    if "referable" in detection_result:
        prompt_lines.append(
            f"- Referable DR: {'Yes' if detection_result['referable'] else 'No'} "
            f"(Probability: {detection_result.get('referable_prob', 'N/A')})"
        )

    if structures:
        prompt_lines.extend([
            "",
            "EXTRACTED RETINAL STRUCTURES & LESIONS:",
            f"- Microaneurysms Detected: {structures.get('microaneurysms', 0)}",
            f"- Hemorrhages Detected: {structures.get('hemorrhages', 0)}",
            f"- Hard Exudate Area: {structures.get('exudate_area_px', 0)} pixels",
            f"- Neovascularization Suspicion: {'YES - Elevated peripapillary density' if structures.get('nv_suspicion') else 'No'}",
            f"- Vessel Density: {structures.get('vessel_density', 0) * 100:.2f}%",
            f"- Vessel Tortuosity Index: {structures.get('tortuosity', 0):.3f}",
        ])

    if localization_metrics:
        prompt_lines.extend([
            "",
            "QUANTITATIVE EXPLAINABILITY (HiResCAM vs Lesions):",
            f"- Localization Metrics: {json.dumps(localization_metrics, indent=2)}",
        ])

    if patient_info:
        prompt_lines.extend([
            "",
            "PATIENT CLINICAL CONTEXT:",
            f"- Age: {patient_info.get('age', 'Not specified')}",
            f"- Diabetes Duration: {patient_info.get('diabetes_duration', 'Not specified')} years",
            f"- Fasting Blood Sugar: {patient_info.get('sugar_level', 'Not specified')} mg/dL",
            f"- HbA1c: {patient_info.get('hba1c', 'Not specified')}%",
        ])
    else:
        prompt_lines.extend([
            "",
            "PATIENT CLINICAL CONTEXT: None provided (use standard population base rates).",
        ])

    prompt_lines.extend([
        "",
        "TASK:",
        "1. Inspect the attached fundus image and HiResCAM saliency heatmap.",
        "2. Formulate your grounded multimodal evaluation adhering strictly to the JSON schema.",
        "3. Provide response strictly as JSON with no markdown wrapping.",
    ])

    return "\n".join(prompt_lines)


def _clean_json_text(text: str) -> str:
    """Strip markdown markers and find JSON boundaries."""
    text = text.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[-1]
    if text.endswith("```"):
        text = text.rsplit("```", 1)[0]
    text = text.strip()
    if text.startswith("json"):
        text = text[4:].strip()

    # Extract JSON object substring if surrounding fluff exists
    start = text.find("{")
    end = text.rfind("}")
    if start != -1 and end != -1 and end > start:
        text = text[start : end + 1]
    return text


def _call_multimodal_api(
    prompt: str,
    base64_fundus: str,
    base64_cam: str | None = None,
    timeout: int = TIER2_TIMEOUT,
) -> dict | None:
    """Call Google Generative Language multimodal endpoint."""
    max_retries = 4
    models_to_try = [MEDGEMMA_MODEL_NAME, GEMMA_MODEL_NAME, "gemini-1.5-flash", "gemini-2.0-flash"]
    # De-duplicate while preserving order
    seen = set()
    models_to_try = [m for m in models_to_try if m and not (m in seen or seen.add(m))]

    parts: list[dict[str, Any]] = [
        {"text": prompt},
        {
            "inlineData": {
                "mimeType": "image/jpeg",
                "data": base64_fundus,
            }
        },
    ]
    if base64_cam:
        parts.append({
            "inlineData": {
                "mimeType": "image/jpeg",
                "data": base64_cam,
            }
        })

    payload = {
        "systemInstruction": {
            "parts": [{"text": MEDGEMMA_SYSTEM_PROMPT}]
        },
        "contents": [
            {
                "role": "user",
                "parts": parts,
            }
        ],
        "generationConfig": {
            "temperature": 0.2,
            "maxOutputTokens": 2500,
            "responseMimeType": "application/json",
        },
    }

    for model in models_to_try:
        for attempt in range(max_retries):
            api_key = get_next_gemma_key()
            if not api_key:
                log.info("No Gemma API key available for Tier 2.")
                return None

            url = GEMMA_API_URL.format(model=model) + f"?key={api_key}"
            try:
                log.info("Attempting Tier 2 MedGemma multimodal call using %s (attempt %d)...", model, attempt + 1)
                resp = requests.post(
                    url,
                    json=payload,
                    headers={"Content-Type": "application/json"},
                    timeout=timeout,
                )

                if resp.status_code == 200:
                    data = resp.json()
                    candidates = data.get("candidates", [])
                    if candidates:
                        text_parts = candidates[0].get("content", {}).get("parts", [])
                        if text_parts:
                            raw_text = text_parts[0].get("text", "")
                            cleaned = _clean_json_text(raw_text)
                            try:
                                return json.loads(cleaned)
                            except json.JSONDecodeError as jde:
                                log.warning("JSON decode failed for model %s: %s", model, jde)
                    log.warning("Empty candidate returned from %s", model)
                    break  # Try next model

                elif resp.status_code == 429:
                    log.warning("Rate limited (429) for key on %s. Rotating key...", model)
                    time.sleep(0.5)
                    continue

                elif resp.status_code in (404, 400):
                    # Model not found or does not support systemInstruction / multimodal format
                    log.warning("Model %s returned HTTP %d: %s. Trying next model.", model, resp.status_code, resp.text[:150])
                    break  # Break attempt loop, try next model

                else:
                    log.warning("API error HTTP %d: %s", resp.status_code, resp.text[:150])
                    time.sleep(0.5)

            except requests.exceptions.Timeout:
                log.warning("Tier 2 request timed out after %ds on attempt %d", timeout, attempt + 1)
            except Exception as e:
                log.warning("Tier 2 request encountered error: %s", e)

    return None


def generate_medgemma_report(
    fundus_image: str | Path | np.ndarray,
    detection_result: dict,
    structures: dict | None = None,
    hirescam_overlay: str | Path | np.ndarray | None = None,
    localization_metrics: dict | None = None,
    patient_info: dict | None = None,
    offline_fallback: bool = True,
) -> tuple[dict, str]:
    """
    Generate Tier 2 MedGemma multimodal report.

    Parameters:
        fundus_image: file path or numpy array of the fundus image.
        detection_result: Tier 1 model outputs (stage, confidence, probs).
        structures: Lesion and vessel stats from structures module.
        hirescam_overlay: Optional HiResCAM or GradCAM visual overlay.
        localization_metrics: Quantitative localization score dict.
        patient_info: Optional patient context (HbA1c, age, duration, etc.).
        offline_fallback: If True, falls back to deterministic offline report.

    Returns:
        tuple[dict, str]: (report_json, source_description)
    """
    if OFFLINE_MODE:
        log.info("OFFLINE_MODE is active — skipping Tier 2 API, using Tier 1 offline generator.")
        report, src = generate_offline_report(
            detection_result=detection_result,
            heatmap_analysis={"most_affected_region": "central", "activity_intensity": "moderate"},
            vessel_stats=structures,
            patient_info=patient_info,
            structures=structures,
        )
        report["tier"] = "Tier 1 (Offline Mode Enforced)"
        return report, src

    try:
        base64_fundus = encode_image_to_base64(fundus_image)
        base64_cam = None
        if hirescam_overlay is not None:
            try:
                base64_cam = encode_image_to_base64(hirescam_overlay)
            except Exception as err:
                log.warning("Could not encode CAM overlay for Tier 2: %s", err)

        prompt = _build_user_prompt(
            detection_result=detection_result,
            structures=structures,
            localization_metrics=localization_metrics,
            patient_info=patient_info,
        )

        t_start = time.time()
        report_data = _call_multimodal_api(prompt, base64_fundus, base64_cam)
        latency = round(time.time() - t_start, 2)

        if report_data and isinstance(report_data, dict) and "current_diagnosis" in report_data:
            report_data["tier"] = "Tier 2 (MedGemma Multimodal)"
            report_data["tier2_latency_s"] = latency
            log.info("Tier 2 MedGemma report successfully generated in %.2fs", latency)
            return report_data, "MedGemma 27B Vision-Language Model (Tier 2 Cloud)"

        log.info("Tier 2 call did not return structured report; initiating Tier 1 fallback.")

    except Exception as exc:
        log.exception("Unexpected error in MedGemma Tier 2 pipeline: %s", exc)

    if offline_fallback:
        report, src = generate_offline_report(
            detection_result=detection_result,
            heatmap_analysis={"most_affected_region": "central", "activity_intensity": "moderate"},
            vessel_stats=structures,
            patient_info=patient_info,
            structures=structures,
        )
        report["tier"] = "Tier 1 (Fallback: Edge Deterministic Rules)"
        report["tier2_fallback_reason"] = "Cloud API unavailable or timed out"
        return report, f"{src} (Tier 2 Fallback)"

    raise RuntimeError("MedGemma Tier 2 generation failed and offline_fallback is False.")
